- name: Clone Application
  git:
    repo: https://github.com/duncaneddy/simple_python_application.git
    dest: ~/ansible_deploy/simple_python_application

- name: Install Application
  shell: python3 install -e .
  args:
    chdir: ~/ansible_deploy

- name: Run Application
  shell: python3 ./simple_app/app.py
  args:
    chdir: ~/ansible_deploy
  environment:
    APP_SECRET: "{{ app_secret }}"