- name: Clone Application
  git:
    repo: git@github.com:duncaneddy/simple_python_application.git
    dest: ~/ansible_deploy/simple_python_application

- name: Install Application
  shell: pip3 install -e .
  args:
    chdir: ~/ansible_deploy/simple_python_application

- name: Run Application
  shell: nohup python3 ./simple_app/app.py &
  args:
    chdir: ~/ansible_deploy/simple_python_application
  environment:
    APP_SECRET: "{{ app_secret }}"